apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep2
  labels:
    app: dep2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dep2

  template:
    metadata:
      labels:
        app: dep2
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
         - containerPort: 80
      initContainers:
      - name: busybox-check
        image: busybox
        command: ['sh', '-c', "until nslookup nginx-svc.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 5; done"]